//
//  ViewController.swift
//  SourceryParsable
//
//  Created by Alexander Nifontov on 24.02.2023.
//

import UIKit

class ViewController: UIViewController {
	
	// MARK: - Subviews
	
	private let lblDescription = UILabel()
	
	// MARK: - Properties
	
	private let sourceryDescription = """
	Проект содержит шаблоны для Sourcery, которые генерируют модели аналогичные ClassGenerator.
	
	При интеграции к себе добавить файл конфигурации .sourcery.yml
	
	Главное отличие заключается в том, что нужно указывать ключи. Объявить enum CodingKeys, который описывает ключи для парсинга, а кейсы совпадают с именем переменной. Если их не объявить, то генерируются автоматически.
	
	После добавления новой модели нужно собрать проект и добавить сгенерировавшийся extension в папку Autogenerated/AutoParsable (при необходимости можно изменить папку назначения).
	
	Для установки sourcery нужно использовать brew.
	brew install sourcery
	"""
	
	// MARK: -  Lifecycle
	
	override func viewDidLoad() {
		super.viewDidLoad()
		
		view.backgroundColor = .systemBackground
		
		navigationItem.title = "Sourcery"
		navigationController?.navigationBar.prefersLargeTitles = true
		
		lblDescription.text = sourceryDescription
		lblDescription.numberOfLines = 0
		lblDescription.translatesAutoresizingMaskIntoConstraints = false
		
		view.addSubview(lblDescription)
		lblDescription.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor).isActive = true
		lblDescription.leadingAnchor.constraint(equalTo: view.layoutMarginsGuide.leadingAnchor).isActive = true
		lblDescription.trailingAnchor.constraint(equalTo: view.layoutMarginsGuide.trailingAnchor).isActive = true
	}
}

